// Generate SQL for the schema
export const generateSQL = (tables, relations) => {
    let sql = "-- SQL Schema generated by DataWeave\n";
    sql += `-- Generated on: ${new Date().toISOString()}\n\n`;
    
    // Generate CREATE TABLE statements
    tables.forEach(table => {
      sql += `CREATE TABLE \`${table.name}\` (\n`;
      
      // Add fields
      const fieldDefinitions = table.fields.map(field => {
        let def = `  \`${field.name}\` ${field.type}`;
        if (field.isNotNull) def += ' NOT NULL';
        if (field.isAutoIncrement) def += ' AUTO_INCREMENT';
        if (field.isPrimaryKey) def += ' PRIMARY KEY';
        return def;
      });
      
      sql += fieldDefinitions.join(',\n');
      sql += '\n);\n\n';
    });
    
    // Generate ALTER TABLE statements for foreign keys
    relations.forEach(relation => {
      const sourceTable = tables.find(t => t.id === relation.sourceTableId);
      const targetTable = tables.find(t => t.id === relation.targetTableId);
      
      if (!sourceTable || !targetTable) return;
      
      const sourceField = sourceTable.fields.find(f => f.id === relation.sourceFieldId);
      const targetField = targetTable.fields.find(f => f.id === relation.targetFieldId);
      
      if (!sourceField || !targetField) return;
      
      sql += `ALTER TABLE \`${targetTable.name}\` ADD FOREIGN KEY (\`${targetField.name}\`) REFERENCES \`${sourceTable.name}\`(\`${sourceField.name}\`);\n`;
    });
    
    return sql;
  };